"""empty message

Revision ID: 9b8efb4de258
Revises: 
Create Date: 2025-09-07 13:54:18.209405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8efb4de258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('src_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('src_currency', sa.String(length=3), nullable=False),
    sa.Column('dst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dst_currency', sa.String(length=3), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=True),
    sa.Column('payee_id', sa.UUID(), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_provider', sa.String(length=64), nullable=False),
    sa.Column('fx_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status'), server_default='CREATED', nullable=False),
    sa.Column('is_reversal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_dst_ccy', 'payments', ['dst_currency'], unique=False)
    op.create_index('ix_payments_payee', 'payments', ['payee_id'], unique=False)
    op.create_index('ix_payments_payer', 'payments', ['payer_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_payer', table_name='payments')
    op.drop_index('ix_payments_payee', table_name='payments')
    op.drop_index('ix_payments_dst_ccy', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
